name = "ease-calendar-user-worker"
main = "src/index.ts"
compatibility_date = "2024-03-04"
node_compat = true

[vars]
ENVIRONMENT = "dev"

[env.staging]
name = "user-staging"
workers_dev = false
route = "ease-calendar-user-worker.gisellehoekveld.workers.dev/*"
[env.staging.vars]
ENVIRONMENT = "staging"
